"""
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
Example 3:

Input: s = "a", t = "aa"
Output: "a"
Example 4:

Input: s = "ae", t = "aea"
Output: "a"


Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lower-case English letters.
"""


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        s = list(s)
        t = list(t)
        for i in range(len(s)):
            for j in range(len(t)):
                if s[i] == t[j]:
                    t.remove(t[j])
                    break
        return t[0]


# arr = []
arr = [["abcd", "abcde"], ["", "y"], ["a", "aa"], ["ae", "aea"]]

sol = Solution()
for el in arr:
    print(sol.findTheDifference(el[0], el[1]))

